site_name: speeding-up-science
site_url: https://speeding-up-science-workshops.github.io/speeding-up-science
repo_name: speeding-up-science
repo_url: https://github.com/speeding-up-science-workshops/speeding-up-science
edit_uri: ""

extra_css: css/custom.css

copyright: 'Copyright &copy; 2019 <a href="http://ivory.idyll.org/lab/">Lab for Data Intensive Biology</a> at UC Davis
<br/><br/>
Icon made by Freepik, obtained from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>, used under a <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons   BY 3.0" target="_blank">CC 3.0 BY</a></div> license.'

# change directory names here
docs_dir: docs
site_dir: site

theme:

  # the next 2 lines are required to use the DIB version
  name: null
  custom_dir: 'mkdocs-material-dib/material'

  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'green'
    accent: 'green'
  
  # fun logos! see https://material.io/icons/
  logo: 'img/baseline_fast_forward_white_18dp.png'

  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# this will add docs/css/custom.css to all your docs
extra_css:
  - css/custom.css

# give a title for each page
nav:
  - 'Home' : 'index.md'
  - 'Metagenomics':
    - 'KEGG Decoder': 'kegg-decoder.md'
    - 'MAG Statistics': 'mag-stats.md'
    - 'MAG Representation': 'mag-representation.md'
  - 'Metatranscriptomics':
    - 'LDA Analysis': 'lda-analysis.md'
    - 'Taxa and Function Summary': 'taxa-and-function-summary.md'
  - 'Metabarcoding':
    - 'Interactive First-Look Barcoding': 'interactive-firstlook-barcoding.md'
  - 'Utilities':
    - 'Editing This Site': 'editing_this_site.md'
    - 'Setting Up mkdocs': 'setting_up_mkdocs.md'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
